### PR TITLE
Correct the missing CSRF for two check methods

### PR DESCRIPTION
**Pull request by Wadeck**
Correct:
Screenshot_2020-03-04_143711_001

### CODE REVIEW

**Comment by mat1e** [comment]
@Wadeck, I never got this error, but your correction works for me.

**Comment by Wadeck** [comment]
@mat1e I hope you have not a disabled CSRF protection on your instance ;)

**Comment by mat1e** [comment]
> 
> 
> @mat1e I hope you have not a disabled CSRF protection on your instance ;)

@Wadeck I checked and I was disabled on my local instance. I enabled it. Thanks !

**Comment by mat1e** [comment]
@Wadeck, have you an idea why I have a warning in jenkins plugin managment for mac-plugin 1.2.1 ?

image

On the plugin page, I see it affect only version 1.1.0 and earlier : 

image

**Comment by Wadeck** [comment]
Hello @mat1e, as it was corrected after the advisory publication you have to create a PR like https://github.com/jenkins-infra/update-center2/pull/278 to update the warnings.json file that is used to inform instances about security warnings.

Do not hesitate to ping me in that PR ;)

**Comment by Wadeck** [comment]
=> https://github.com/jenkins-infra/update-center2/pull/391 to remove the 1.2.1 version from the warning.

**Comment by mat1e** [comment]
Thank you @Wadeck for your actions !

**Pull request merged**
